[colors.normal]
black =   '0x002b36'
red =     '0xcb4b16'
green =   '0x859900'
yellow =  '0xb58900'
blue =    '0x268bd2'
magenta = '0xd33682'
cyan =    '0x2aa198'
white =   '0x839496'

[colors.bright]
black =   '0x073642'
red =     '0xcb4b16'
green =   '0x859900'
yellow =  '0xb58900'
blue =    '0x268bd2'
magenta = '0xd33682'
cyan =    '0x2aa198'
white =   '0x839496'

[colors.cursor]
cursor = "0x839496"
text = "0x002b36"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[cursor.style]
blinking = "Never"

[font]
size = 10.5

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

#[keyboard]
#bindings = [
#{ key = "C", mods = "Control", action = "Copy" },
#{ key = "V", mods = "Control", action = "Paste" },
#{ key = "C", mods = "Control|Shift", chars = "\u0003"}
#]
